/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPackage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author SHOAIB SHAIKH
 */
public class Suit extends javax.swing.JFrame {

    /**
     * Creates new form CustomerRegistration
     */
    public Suit() {
        initComponents();
        setResizable(false);
    }
        private Connection con = null;
        private PreparedStatement ps = null;
        private ResultSet rr = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        height = new javax.swing.JLabel();
        chest = new javax.swing.JLabel();
        stomach = new javax.swing.JLabel();
        hip = new javax.swing.JLabel();
        height1 = new javax.swing.JTextField();
        chest1 = new javax.swing.JTextField();
        stomach1 = new javax.swing.JTextField();
        hip1 = new javax.swing.JTextField();
        collar = new javax.swing.JLabel();
        shoulder = new javax.swing.JLabel();
        hand = new javax.swing.JLabel();
        cup = new javax.swing.JLabel();
        shoulder1 = new javax.swing.JTextField();
        hand1 = new javax.swing.JTextField();
        cup1 = new javax.swing.JTextField();
        collar1 = new javax.swing.JTextField();
        quantity1 = new javax.swing.JLabel();
        price1 = new javax.swing.JLabel();
        order_date = new javax.swing.JTextField("yyyy-mm-dd");
        delivery_date = new javax.swing.JTextField("yyyy-mm-dd");
        orderdate = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        deliverydate = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        search_field = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NEW CUSTOMER");

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        jButton2.setBackground(new java.awt.Color(0, 153, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("HOME");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SUIT MEASUREMENT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 20));

        height.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        height.setText("Height:");

        chest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chest.setText("Chest:");

        stomach.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stomach.setText("Stomach:");

        hip.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hip.setText("Hip:");

        height1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        height1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                height1ActionPerformed(evt);
            }
        });

        chest1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chest1ActionPerformed(evt);
            }
        });

        stomach1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        hip1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hip1ActionPerformed(evt);
            }
        });

        collar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        collar.setText("Collar:");

        shoulder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        shoulder.setText("Shoulder:");

        hand.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hand.setText("Hand:");

        cup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cup.setText("Cup:");

        shoulder1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        shoulder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoulder1ActionPerformed(evt);
            }
        });

        hand1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hand1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hand1ActionPerformed(evt);
            }
        });

        cup1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cup1ActionPerformed(evt);
            }
        });

        collar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        collar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collar1ActionPerformed(evt);
            }
        });

        quantity1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        quantity1.setText("Quantity:");

        price1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        price1.setText("Price:");

        order_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        order_date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                order_dateFocusGained(evt);
            }
        });
        order_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_dateActionPerformed(evt);
            }
        });

        delivery_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delivery_date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                delivery_dateFocusGained(evt);
            }
        });
        delivery_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delivery_dateActionPerformed(evt);
            }
        });

        orderdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        orderdate.setText("Order Date:");

        quantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });

        deliverydate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deliverydate.setText("Delivery Date:");

        price.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hand, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(shoulder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(collar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chest, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(quantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderdate)
                    .addComponent(deliverydate)
                    .addComponent(hip, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stomach, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(price, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(quantity)
                    .addComponent(collar1)
                    .addComponent(chest1)
                    .addComponent(stomach1)
                    .addComponent(hip1)
                    .addComponent(shoulder1)
                    .addComponent(hand1)
                    .addComponent(cup1)
                    .addComponent(order_date)
                    .addComponent(delivery_date)
                    .addComponent(height1))
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(height1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(height))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chest))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stomach1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stomach))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hip))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shoulder)
                    .addComponent(shoulder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hand)
                    .addComponent(hand1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cup1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cup))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(collar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(collar))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(order_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderdate))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delivery_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deliverydate))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantity1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price)
                    .addComponent(price1))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Enter Mobile no. to search:");

        search_field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_fieldActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Click To Search");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 20));

        jButton6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton6.setText("SAVE");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton5.setText("RESET");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton8.setText("REPORT");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton7.setText("UPDATE");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton10.setText("BACK");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 65, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chest1ActionPerformed

    private void height1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_height1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_height1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   new HomeFrame().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void search_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_fieldActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
  height1.setText(null);   
    chest1.setText(null); 
 stomach1.setText(null); 
 hip1.setText(null); 
 shoulder1.setText(null); 
 hand1.setText(null); 
  cup1.setText(null); 
   collar1.setText(null); 
    order_date.setText(null); 
     delivery_date.setText(null); 
      quantity.setText(null);
       price.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
if(height.getText().isEmpty() || chest.getText().isEmpty() || stomach.getText().isEmpty() || hip.getText().isEmpty() || shoulder.getText().isEmpty() || hand.getText().isEmpty() || cup.getText().isEmpty() || collar.getText().isEmpty() || orderdate.getText().isEmpty() || deliverydate.getText().isEmpty() || quantity.getText().isEmpty() || price.getText().isEmpty())
   {
   JOptionPane.showMessageDialog(this,"Empty field found. Enter all field.!!!","Wrong!!",JOptionPane.INFORMATION_MESSAGE);
   } 
   else
   {    
       
       try
       {
      
   
            con = DBConnection.getConnection();
            String query;
 query = "INSERT INTO SHOAIB.suit ( mobile,HEIGHT, CHEST, STOMACH, HIP, SHOULDER, HAND, CUP, COLLAR, ORDER_DATE, DELIVERY_DATE,quantity,price) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";

                ps=con.prepareStatement(query);
                ps.setString(1,NewCustomer.mobile_field.getText());
                ps.setString(2,(height1.getText()));
                ps.setString(3,(chest1.getText()));
                ps.setString(4, (stomach1.getText()));
                ps.setString(5, (hip1.getText()));
                ps.setString(6, (shoulder1.getText()));
                ps.setString(7, (hand1.getText()));
                ps.setString(8, (cup1.getText()));
                ps.setString(9, (collar1.getText()));
                ps.setString(10, order_date.getText());
                ps.setString(11, delivery_date.getText());
                ps.setString(12,(quantity.getText()));
                ps.setString(13,(price.getText()));               
                boolean execute = ps.execute();
                JOptionPane.showMessageDialog(this,"Saved Successfully","Successful!!!",JOptionPane.INFORMATION_MESSAGE);
                
     ps.close();
     con.close();
   } 
   catch (SQLException ex) 
   {
            System.out.println(ex);
   }
   }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
   new SuitReport().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void hip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hip1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hip1ActionPerformed

    private void shoulder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoulder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shoulder1ActionPerformed

    private void hand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hand1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hand1ActionPerformed

    private void cup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cup1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cup1ActionPerformed

    private void collar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collar1ActionPerformed

    private void order_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_order_dateActionPerformed

    private void delivery_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delivery_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delivery_dateActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       new Measurement().setVisible(true);       
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     
    DBConnection.getConnection();
    DatabaseSearch d=new DatabaseSearch();
    rr = d.findSuit(search_field.getText());
    
    try
    {
      rr.next();
      {
          rr.getInt(1);
          rr.getString(2);
          height1.setText(String.valueOf(rr.getInt(3)));
          chest1.setText(String.valueOf(rr.getInt(4)));
          stomach1.setText(String.valueOf(rr.getInt(5)));
          hip1.setText(String.valueOf(rr.getInt(6)));
          shoulder1.setText(String.valueOf(rr.getInt(7)));
          hand1.setText(String.valueOf(rr.getInt(8)));
          cup1.setText(String.valueOf(rr.getInt(9)));
          collar1.setText(String.valueOf(rr.getInt(10)));
          order_date.setText(String.valueOf(rr.getDate(11)));
          delivery_date.setText(String.valueOf(rr.getDate(12)));
          quantity.setText(String.valueOf(rr.getInt(13)));
          price.setText(String.valueOf(rr.getInt(14)));
          
          rr.close();
          con.close();
      } 
    
    }
    catch(Exception ex)
    {
           System.out.println(ex);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void order_dateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_order_dateFocusGained
order_date.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_order_dateFocusGained

    private void delivery_dateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_delivery_dateFocusGained
delivery_date.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_delivery_dateFocusGained

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                
       try
        {     
              
    String a1= order_date.getText();             
    java.sql.Date d1 = java.sql.Date.valueOf(a1);
                          
    String a2= delivery_date.getText();             
    java.sql.Date d2 = java.sql.Date.valueOf(a2);
    
    con=DBConnection.getConnection();
    String query;
    query= "update suit set HEIGHT="+height1.getText()+",CHEST="+chest1.getText()+",STOMACH="+
            stomach1.getText()+",HIP="+hip1.getText()+",SHOULDER="+shoulder1.getText()+
            ",HAND="+hand1.getText()+",CUP="+cup1.getText()+",COLLAR="+collar1.getText()+
            ",quantity="+quantity.getText()+",price="+price.getText()+",ORDER_DATE='"+d1+"'"+",delivery_date='"+d2+"'"+
            "where mobile='"+search_field.getText()+"'";
     
    ps=con.prepareStatement(query);
    ps.execute();
    JOptionPane.showMessageDialog(this,"Updated Successfully","Successful!!!",JOptionPane.INFORMATION_MESSAGE);
                
    }
    catch(Exception e)
    {
    System.out.println(e);
    }
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Suit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Suit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Suit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Suit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Suit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chest;
    private javax.swing.JTextField chest1;
    private javax.swing.JLabel collar;
    private javax.swing.JTextField collar1;
    private javax.swing.JLabel cup;
    private javax.swing.JTextField cup1;
    private javax.swing.JTextField delivery_date;
    private javax.swing.JLabel deliverydate;
    private javax.swing.JLabel hand;
    private javax.swing.JTextField hand1;
    private javax.swing.JLabel height;
    private javax.swing.JTextField height1;
    private javax.swing.JLabel hip;
    private javax.swing.JTextField hip1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField order_date;
    private javax.swing.JLabel orderdate;
    private javax.swing.JTextField price;
    private javax.swing.JLabel price1;
    private javax.swing.JTextField quantity;
    private javax.swing.JLabel quantity1;
    private javax.swing.JTextField search_field;
    private javax.swing.JLabel shoulder;
    private javax.swing.JTextField shoulder1;
    private javax.swing.JLabel stomach;
    private javax.swing.JTextField stomach1;
    // End of variables declaration//GEN-END:variables
}
